from __future__ import annotations

REVIEW_ACTION_CREATE_NEW_SKU = "create_new_sku"
REVIEW_ACTION_BIND_EXISTING_SKU = "bind_existing_sku"
REVIEW_ACTION_ADD_HARD_CASE_SAMPLE = "add_hard_case_sample"
REVIEW_ACTION_REJECT_INVALID_IMAGE = "reject_invalid_image"

REGISTRATION_REVIEW_ACTIONS = [
    REVIEW_ACTION_CREATE_NEW_SKU,
    REVIEW_ACTION_BIND_EXISTING_SKU,
    REVIEW_ACTION_REJECT_INVALID_IMAGE,
]

IDENTIFICATION_REVIEW_ACTIONS = [
    REVIEW_ACTION_BIND_EXISTING_SKU,
    REVIEW_ACTION_ADD_HARD_CASE_SAMPLE,
    REVIEW_ACTION_REJECT_INVALID_IMAGE,
]
